region = "us-west1"
zone = "us-west1-c"
project = "sylerseclearn2022-348606"
username = "kishorekumarbehera"
k8smaster_script_path = "/Users/kishorekumarbehera/Desktop/Tools/SYLER_GITHUB/K8SeasywayGCP/scripts/k8smaster_bootstrap.sh"
k8sworker_script_path = "/Users/kishorekumarbehera/Desktop/Tools/SYLER_GITHUB/K8SeasywayGCP/scripts/k8sworker_bootstrap.sh"
private_key_path = "/Users/kishorekumarbehera/.ssh/id_rsa"