region                = "us-west1"
zone                  = "us-west1-c"
project               = "kishore-k8s-project"
username              = "kishore_behera2010"
k8smaster_script_path = "/home/kishore_behera2010/K8SeasywayGCP/scripts/latest/k8smaster_bootstrap.sh"
k8sworker_script_path= "/home/kishore_behera2010/K8SeasywayGCP/scripts/latest/k8sworker_bootstrap.sh"
private_key_path      = "/home/kishore_behera2010/.ssh/id_rsa"
